<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>similar-products-web-boot</artifactId>
  <packaging>jar</packaging>
  <name>similar-products-web-boot</name>


  <parent>
    <groupId>com.example.similarproducts</groupId>
    <artifactId>similar-products-web</artifactId>
    <version>0.1.0</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>com.example.similarproducts</groupId>
      <artifactId>similar-products-web-api-rest</artifactId>
    </dependency>

    <dependency>
      <groupId>com.example.similarproducts</groupId>
      <artifactId>similar-products-web-rest-repository</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <!-- Provides support to package and run applications "in-place" -->
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>

       <!-- Assembly Build info on final artefact-->
      <plugin>
		 <groupId>org.codehaus.mojo</groupId>
		 <artifactId>exec-maven-plugin</artifactId>
	  </plugin>
    </plugins>
  </build>

</project>
